obj-$(CONFIG_PANEL_GENERIC) += panel-generic.o
obj-$(CONFIG_PANEL_VGA) += panel-vga.o
obj-$(CONFIG_PANEL_SAMSUNG_LTE430WQ_F0C) += panel-samsung-lte430wq-f0c.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_SHARP_SPI_LCD) += panel-sharp-lq025q3dw02.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_TFP410)		+= tfp410.o
obj-$(CONFIG_THS8200)		+= ths8200.o

